Repository JayDampitan/news-app, pull requests merged in 2021-09, with the labels that each got.

#51 Search Page Pagination and Styling
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
Labels: enhancement

#53 Movie Article Layout
  .vscode/settings.json
  the-toad-tribune/src/commons/articleDesign.ts
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/layout/Movies.tsx
Labels: enhancement

#56 Make Cursor a Pointer
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
Labels: enhancement

#58 Handle Search Validations
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
Labels: enhancement

#59 Weather Component Styling
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/assets/telebabysun.png
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#61 Refactor Modules File
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/api/adsApi.ts
  the-toad-tribune/src/api/index.ts
  the-toad-tribune/src/api/newsApi.ts
  the-toad-tribune/src/api/weatherApi.ts
  the-toad-tribune/src/layout/Ads.tsx
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/MoreInfo.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#63 Custom Snackbar w/Server Errors
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/api/newsApi.ts
  the-toad-tribune/src/components/Snackbar.tsx
  the-toad-tribune/src/components/index.ts
Labels: enhancement

#64 More Info Styling
  the-toad-tribune/src/layout/MoreInfo.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/utils/loremIpsum.ts
Labels: enhancement

#66 Articles Content Layout
  the-toad-tribune/src/assets/toad.png
  the-toad-tribune/src/commons/articleDesign.ts
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/commons/index.js
  the-toad-tribune/src/index.css
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/Layout.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#68 Main Article Layout
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Navgation.tsx
Labels: enhancement

#69 Dark Theme
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/api/newsApi.ts
  the-toad-tribune/src/api/weatherApi.ts
  the-toad-tribune/src/assets/toadTribuneDark.svg
  the-toad-tribune/src/assets/toadTribuneLight.svg
  the-toad-tribune/src/commons/darkMode.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/Layout.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/MoreInfo.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#74 Convert Publish Dates
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/MoreInfo.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/utils/dateConverter.ts
Labels: enhancement

#77 Articles Style Adjustments
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#83 Typography
  the-toad-tribune/public/index.html
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Navgation.tsx
Labels: enhancement

#84 Pagination Bugs
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/assets/next-button.svg
  the-toad-tribune/src/assets/prev-button.svg
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
Labels: bug

#87 Update Loaders
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/index.css
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
Labels: enhancement

#90 Updating Meta Tags and Manifest.json
  the-toad-tribune/public/apple-touch-icon.png
  the-toad-tribune/public/favicon.ico
  the-toad-tribune/public/index.html
  the-toad-tribune/public/logo192.png
  the-toad-tribune/public/logo512.png
  the-toad-tribune/public/manifest.json
  the-toad-tribune/src/assets/dark-logo.png
  the-toad-tribune/src/assets/light-logo.png
  the-toad-tribune/src/layout/Navgation.tsx
Labels: enhancement

#91 Sun Animation
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: enhancement

#92 Add Alt descriptions
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
Labels: enhancement

#94 docs(readme): update README.md
  README.md
Labels: documentation

#97 Fix Buttons to Appear
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
Labels: bug

#100 Movie Component Styling
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/commons/articleDesign.ts
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Politics.tsx
Labels: bug, enhancement

#106 Fix Navbar Responsive
  the-toad-tribune/src/layout/Navgation.tsx
Labels: bug

#107 Details Page Responsive
  the-toad-tribune/src/layout/MoreInfo.tsx
Labels: bug

#108 Fixed Homepage Responsiveness
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/Layout.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
Labels: bug

#110 Search Page Responsive
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/layout/Layout.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
Labels: bug

#111 Fixed NewsAPI Handler
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/api/newsApi.ts
  the-toad-tribune/src/layout/SearchResults.tsx
Labels: bug

#112 Merge Development to Main
  the-toad-tribune/package-lock.json
  the-toad-tribune/package.json
  the-toad-tribune/src/SubApp.tsx
  the-toad-tribune/src/api/adsApi.ts
  the-toad-tribune/src/api/index.ts
  the-toad-tribune/src/api/newsApi.ts
  the-toad-tribune/src/app/hooks.ts
  the-toad-tribune/src/app/store.ts
  the-toad-tribune/src/commons/articleDesign.ts
  the-toad-tribune/src/commons/articleDesign2.ts
  the-toad-tribune/src/commons/buttons.ts
  the-toad-tribune/src/features/counter/Counter.module.css
  the-toad-tribune/src/features/counter/Counter.tsx
  the-toad-tribune/src/features/counter/counterAPI.ts
  the-toad-tribune/src/features/counter/counterSlice.spec.ts
  the-toad-tribune/src/features/counter/counterSlice.ts
  the-toad-tribune/src/index.tsx
  the-toad-tribune/src/layout/Ads.tsx
  the-toad-tribune/src/layout/Animals.tsx
  the-toad-tribune/src/layout/Layout.tsx
  the-toad-tribune/src/layout/MainArticle.tsx
  the-toad-tribune/src/layout/MoreInfo.tsx
  the-toad-tribune/src/layout/Movies.tsx
  the-toad-tribune/src/layout/Navgation.tsx
  the-toad-tribune/src/layout/Politics.tsx
  the-toad-tribune/src/layout/SearchResults.tsx
  the-toad-tribune/src/layout/Sports.tsx
  the-toad-tribune/src/layout/Stonks.tsx
  the-toad-tribune/src/layout/Weather.tsx
  the-toad-tribune/src/layout/index.tsx
Labels: enhancement

#114 Fix Font Link
  the-toad-tribune/public/index.html
Labels: bug

#115 Version bump
  the-toad-tribune/.firebase/hosting.YnVpbGQ.cache
  the-toad-tribune/.firebaserc
  the-toad-tribune/firebase.json
  the-toad-tribune/package.json
Labels: documentation
